#include "turboquant/codebook.hpp"

#include "codebook_index.hpp"  // generated by CMake — kCodebookBlobs[]

#include <cctype>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>

namespace turboquant {
namespace {

// -----------------------------------------------------------------------------
// Minimal JSON-array-of-floats parser. The codebook JSON format is fixed:
//   { "centroids": [..], "boundaries": [..], "mse_per_coord": .., "mse_total": ..,
//     "d": .., "bits": .. }
// We don't need a general parser; just locate keys and read float arrays /
// scalars. Keeps the library dependency-free for automotive deployment.
// -----------------------------------------------------------------------------
class StringScanner {
public:
    StringScanner(const char* s, size_t n) : s_(s), n_(n) {}

    void skip_ws() {
        while (i_ < n_ && std::isspace(static_cast<unsigned char>(s_[i_]))) ++i_;
    }

    bool find_key(const char* key) {
        const std::string needle = std::string("\"") + key + "\"";
        size_t pos = 0;
        for (size_t i = 0; i + needle.size() <= n_; ++i) {
            if (std::memcmp(s_ + i, needle.data(), needle.size()) == 0) {
                pos = i + needle.size();
                i_ = pos;
                return true;
            }
        }
        return false;
    }

    void expect_colon() {
        skip_ws();
        if (i_ < n_ && s_[i_] == ':') ++i_;
    }

    double read_number() {
        skip_ws();
        char* end = nullptr;
        double v = std::strtod(s_ + i_, &end);
        i_ = static_cast<size_t>(end - s_);
        return v;
    }

    // Read a JSON array of numbers. Returns floats.
    std::vector<float> read_float_array() {
        std::vector<float> out;
        skip_ws();
        if (i_ >= n_ || s_[i_] != '[') return out;
        ++i_;  // [
        while (i_ < n_) {
            skip_ws();
            if (s_[i_] == ']') { ++i_; break; }
            char* end = nullptr;
            double v = std::strtod(s_ + i_, &end);
            out.push_back(static_cast<float>(v));
            i_ = static_cast<size_t>(end - s_);
            skip_ws();
            if (i_ < n_ && s_[i_] == ',') ++i_;
        }
        return out;
    }

private:
    const char* s_;
    size_t      n_;
    size_t      i_ = 0;
};

Codebook parse_codebook_json(const unsigned char* data, size_t size, int d, int bits) {
    Codebook cb;
    cb.d = d;
    cb.bits = bits;

    const char* s = reinterpret_cast<const char*>(data);
    {
        StringScanner sc(s, size);
        if (sc.find_key("centroids")) {
            sc.expect_colon();
            cb.centroids = sc.read_float_array();
        }
    }
    {
        StringScanner sc(s, size);
        if (sc.find_key("boundaries")) {
            sc.expect_colon();
            cb.boundaries = sc.read_float_array();
        }
    }
    {
        StringScanner sc(s, size);
        if (sc.find_key("mse_per_coord")) {
            sc.expect_colon();
            cb.mse_per_coord = static_cast<float>(sc.read_number());
        }
    }
    {
        StringScanner sc(s, size);
        if (sc.find_key("mse_total")) {
            sc.expect_colon();
            cb.mse_total = static_cast<float>(sc.read_number());
        }
    }

    // Strip first and last (±1.0) — keep only the interior decision boundaries.
    if (cb.boundaries.size() >= 2) {
        cb.decision_boundaries.assign(cb.boundaries.begin() + 1,
                                      cb.boundaries.end()   - 1);
    }
    return cb;
}

// Lazy-loaded cache of parsed codebooks.
struct PairKey {
    int d;
    int bits;
    bool operator==(const PairKey& o) const { return d == o.d && bits == o.bits; }
};
struct PairKeyHash {
    size_t operator()(const PairKey& k) const noexcept {
        return (static_cast<size_t>(k.d) << 8) ^ static_cast<size_t>(k.bits);
    }
};

std::unordered_map<PairKey, Codebook, PairKeyHash>& cache() {
    static std::unordered_map<PairKey, Codebook, PairKeyHash> m;
    return m;
}
std::mutex& cache_mu() {
    static std::mutex m;
    return m;
}

}  // namespace

const Codebook* get_codebook(int d, int bits) {
    PairKey k{d, bits};
    {
        std::lock_guard<std::mutex> g(cache_mu());
        auto it = cache().find(k);
        if (it != cache().end()) return &it->second;
    }

    for (size_t i = 0; i < detail::kCodebookBlobsCount; ++i) {
        const auto& b = detail::kCodebookBlobs[i];
        if (b.d == d && b.bits == bits) {
            Codebook cb = parse_codebook_json(b.data, b.size, d, bits);
            std::lock_guard<std::mutex> g(cache_mu());
            auto [it, _] = cache().emplace(k, std::move(cb));
            return &it->second;
        }
    }
    return nullptr;
}

std::vector<CodebookKey> available_codebooks() {
    std::vector<CodebookKey> out;
    out.reserve(detail::kCodebookBlobsCount);
    for (size_t i = 0; i < detail::kCodebookBlobsCount; ++i) {
        out.push_back({detail::kCodebookBlobs[i].d, detail::kCodebookBlobs[i].bits});
    }
    return out;
}

}  // namespace turboquant
